# Gateway configuration
gateway_interface: "eth0"

# Caddy reverse proxy hosts
caddy_hosts:
  - domain: "uptime.{{ domain }}"
    backend: "10.0.0.51"
    port: 3001

# WireGuard configuration - client connecting to home network
wireguard_mode: "client"
wireguard_address: "192.168.12.2/32"
wireguard_dns: "192.168.12.1"
wireguard_endpoint: "server.mhlab.me:51820"
wireguard_server_public_key: "CPYgwb54Ciard/gBqdIgJ9N3AOxpP7InWjsSqM1IPm4="

# CoreDNS
dns_records:
  gateway: "{{ gateway_ip }}"
  uptime-kuma: "10.0.0.51"

# nftables
nftables_forward_ports:
  - proto: tcp
    dport: 80
    dest: "{{ gateway_ip }}"
    dest_port: 80
  - proto: tcp
    dport: 443
    dest: "{{ gateway_ip }}"
    dest_port: 443
  - proto: udp
    dport: 51820
    dest: "{{ gateway_ip }}"
    dest_port: 51820
