caddy_hosts:
- backend: 10.0.0.60
  domain: coolify-h.mhlab.me
  port: 8000
  scheme: http
- backend: 10.0.0.1
  domain: proxmox.mhlab.me
  port: 8006
  scheme: https
- backend: 10.0.0.51
  domain: uptime.mhlab.me
  port: 3001
  scheme: http
dns_records:
  coolify: 10.0.0.60
  gateway: 10.0.0.10
  proxmox: 10.0.0.1
  uptime-kuma: 10.0.0.51
