#cloud-config
users:
  - name: root
    ssh_authorized_keys:
      - ${ssh_public_key}
    lock_passwd: true
  - name: mohsin
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_public_key}
    lock_passwd: true
ssh_pwauth: false
packages:
  - qemu-guest-agent
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
