---
# Gateway playbook - configure gateway only

- name: Configure gateway
  hosts: gateway
  vars_files:
    - ../inventory/group_vars/gateway_services.yml
  roles:
    - common
    - gateway_network
    - caddy
    - wireguard
    - dns
