# Shared variables for all hosts
domain: "mhlab.me"
internal_domain: "internal.mhlab.me"
private_subnet: "10.0.0.0/24"
gateway_ip: "10.0.0.10"

# DNS resolver for all VMs
dns_servers:
  - "{{ gateway_ip }}"

# Timezone
timezone: "UTC"

# Admin user (base_user role) - SSH public key for key-only sudo access.
mohsin_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMz/z3teYrXid/cPA6VBTEW6BcObOE9/u9aENFP7lXAH mohsin@infra"

# Common packages
common_packages:
  - curl
  - wget
  - vim
  - htop
  - net-tools
  - dnsutils
  - jq
  - unzip
  - sudo
  - systemd
